name: "Closure Linter - ESLint Plugin and Config"
repository: "google/eslint-closure"
exclude: [
  'node_modules',
  'eslint-repo',
  'vendor'
]
description: "An ESLint plugin and config for Closure JavaScript following Google's style guide."
url: https://google.github.io/eslint-closure
kramdown:
  input: GFM
  toc_levels: 2..3
