name: "ESLint - Pluggable JavaScript linter"
repository: "jschaf/googlejs"
exclude: [
  'node_modules',
  'bower_components',
  'vendor'
]
description: "A pluggable and configurable linter tool for identifying and reporting on patterns in JavaScript. Maintain your code quality with ease."
url: http://eslint.org
kramdown:
  input: GFM
  toc_levels: 2..3
